### ISSUE TITLE
Pretrained word and compound vectors

### ISSUE THREAD

**Issue by sasaadi** [meghdadFar/non-compositionality#1]
Hi Meghdad,

Thanks a lot for providing the source codes of your EMNLP2015 paper.

Actually, this is not an issue, but I did not find your contact details to send you an Email.

I am just wondering if you could also provide the pre-trained word and compound vectors on which you trained and evaluated your model (as described in section 3 of your paper) as a separate file? or if you have got them from any other resources, that would be great to share the link.

Merci,
Shima

**Comment by meghdadFar** [comment]
Hi Shima, 

I don't have the exact same vectors on which the evaluation presented in the paper was carried out. 
However, you can easily create your own vectors using [fastText](https://github.com/facebookresearch/fastText). It is very efficient and fast. 

I have added a preprocessing module that you can use to replace the compounds in your corpus and then pass the corpus to fastText so that it creates word embeddings for both words and compounds. 

I just added instructions on how to create your embeddings and use them to train your regression model in the README file. 

Cheers,
Meghdad

**Comment by sasaadi** [comment]
Thanks a lot for the instructions, Meghdad.

I could run the whole program over the sample data.

I am just a bit confused by the training set and "concatenate compounds" step. 

In order to generate the training compounds, I downloaded the English Wikipedia dump as my corpus and extracted the compounds (as mentioned in the paper- using word2vec and word2phrase). Should I now use the extracted compounds as my training set and run the `replace-compounds.py` on it and the wikipedia corpus? 

Thanks,
Shima

**Comment by meghdadFar** [comment]
Yes, that's right. 
Since for those compounds we need embeddings, before executing word2vec/fasttext we should first replace them in the corpus with their concatenated version (house call --> house_call) so that word2vec identifies them as a token and creates embeddings for them. 
What is word2phrase by the way? Does it create embedding for phrases?

**Comment by sasaadi** [comment]
Thanks!
Word2phrase only replaces the similar words as a compound (like new york to new_york) in the corpus. I just used word2phrase to create a training set, though not sure if it makes sense to do so. Actually, I did not find any other way to create a training set. Anyways, I guess I need to run `replace-compounds.py` instead of word2phase to be able to replace the training and test compounds in the corpus.

**Comment by meghdadFar** [comment]
It seems that word2phrase works by replacing highly associated words in the corpus. Technically you can use it instead of `replace-compounds.py` but then it only replaces collocations and not non-collocational compositional compounds. This may somehow defy the purpose of learning to compose semantics from compositional phrases. To create the training set that is in this repository, I extracted noun-noun compounds from POS tagged corpus and discarded very low-frequency compounds.
